const CONSTANTS = {
  RANDOM_CHAR_SET_UPPER_CASE: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ',
  RANDOM_CHAR_SET: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz',
};

CONSTANTS.CONTROL_STATUS = {
  INACTIVE: 1,
  ACTIVE: 2,
};


module.exports = CONSTANTS;
